### ISSUE TITLE
Never trust user input.

### ISSUE THREAD

**Issue by danmarsden** [fmido88/moodle-paygw_paymob#1]
You have some incorrect use of PARAM_RAW in callback.php and you also have areas in that file that gets the raw data from $_GET and $_POST type calls but do not santise the values before you use them.

please use clean_param() or other apis to make sure the data is in an expected form before you use it.

Note: this is part of our security checklist and therefore is a blocker for plugins db approval

**Comment by fmido88** [comment]
I used PARAM_TEXT instead and for the case of $_GET usage I created a loop to sanitize it.
