### ISSUE TITLE
lang file should only contain english strings.

### ISSUE THREAD

**Issue by danmarsden** [fmido88/moodle-paygw_paymob#4]
https://github.com/fmido88/moodle-paygw_paymob/blob/main/lang/en/paygw_paymob.php#L54

on approval in the plugins db - all strings are passed to our translation tool "AMOS" to allow users to translate them. Best to remove this string from the lang file as it will get very confusing for people using AMOS.

You can include an Arabic lang pack in your plugin if you want to, although it is typically easier to get AMOS to manage the strings and do the translation via the AMOS site when your plugin has been accepted.

Note this is a blocker for plugins db approval.

**Comment by fmido88** [comment]
Thanks, I used it as this payment provider only exist in Arabic nations, but now I separated the lang strings in two different files.
