### ISSUE TITLE
please do not call curl_init direclty and use core "curl" class instead.

### ISSUE THREAD

**Issue by danmarsden** [fmido88/moodle-paygw_paymob#5]
https://github.com/fmido88/moodle-paygw_paymob/blob/main/classes/paymob_helper.php#L76

Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions and takes care of various security and proxy settings within Moodle - it's not documented well, but do a search on core code for "curl" to see it's usage.

**Comment by fmido88** [comment]
Yes, thank you. I didn't know about it until the approval of enrol_wallet, I fixed that here too.
