### ISSUE TITLE
missing external_location_link component of privacy api

### ISSUE THREAD

**Issue by danmarsden** [fmido88/moodle-paygw_paymob#6]
your plugin seems to send email/firstname/lastname/country/phone number/city to the external payment gateway - this needs to be documented in the external_location_link part of the privacy api.

more info on this is here:
https://moodledev.io/docs/apis/subsystems/privacy#indicating-that-you-export-data-to-an-external-location

**Comment by fmido88** [comment]
Thanks, I added it. But this is the first time I read this documentation, so I'm not sure if this is the correct way or not.
I'll be very grateful if you took another look.

**Comment by danmarsden** [comment]
it looks like it's close enough to pass the approval blocker, however it's not quite right in terms of fully compliant privacy api - the get_metadata function should include information on both your tables as they contain "userid" fields and therfore are classed as user data - then the export and delete functions within the privacy api class should allow that data to be delted and exported.

but... the bare miniumum - having the external location data stuff defined is probably enough to get through the approval blocker side of the privacy api.
